Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,7 +10,7 @@ jobs:
   build:
     strategy:
       matrix:
-        php: ['7.2', '7.3', '7.4']
+        php: ['7.2']
 #        include:
 #            - php: '8.0'
 #              composer-flags: '--ignore-platform-req=php'
@@ -18,24 +18,28 @@ jobs:
 
     runs-on: ubuntu-latest
 
-    services:
-      siriusorm_mysql:
-        image: mysql:5.7
-        env:
-          MYSQL_ROOT_PASSWORD: rootpass
-          MYSQL_DATABASE: siriusorm
-        ports:
-          - 3306
-        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
+#     services:
+#       siriusorm_mysql:
+#         image: mysql:5.7
+#         env:
+#           MYSQL_ROOT_PASSWORD: rootpass
+#           MYSQL_DATABASE: siriusorm
+#         ports:
+#           - 3306
+#         options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
 
     steps:
     - uses: actions/checkout@v2
 
+    - uses: mirromutth/mysql-action@v1.1
+      with:
+        mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
+        mysql database: 'siriusorm' # Optional, default value is "test". The specified database which will be create
+        mysql root password: 'rootpass' # Required if "mysql user" is empty, default is empty. The root superuser password
+
     - name: Verify MySQL connection
-      env:
-        PORT: ${{ job.services.siriusorm_mysql.ports[3306] }}
       run: |
-        while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
+        while ! mysqladmin ping -h"127.0.0.1" -P3306 --silent; do
           sleep 1
         done
 
@@ -63,6 +67,8 @@ jobs:
       run: composer install --prefer-dist --no-progress --no-suggest
 
     - name: Run test suite
+      env:
+        MYSQL_CONNECTION: 'mysql:host=localhost;dbname=siriusorm'
       run: |
         mkdir -p build/logs
         vendor/bin/phpunit
